### login
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "userId": "jeehwan98",
  "password": "123123123"
}

### register
POST http://localhost:8080/api/v1/register
Content-Type: application/json
Accept: */*

{
  "userId": "jeehwan98",
  "name": "김지환",
  "password": "123123123",
  "email": "jeehwan@example.com",
  "imageUrl": "imageUrl~"
}

### get currently logged in user
GET http://localhost:8080/api/v1/user
Content-Type: application/json
Accept: */*

### get currently logged in user
GET http://localhost:8080/api/v1/jeehwan98
Content-Type: application/json
Accept: */*
